### PR TITLE
[hotfix] create enrolment updater

### PR DESCRIPTION
**Pull request by michellemtchai**
- enhancement mentioned in issue #177 
- add/rename attributes to `Position` model
  - `current_enrollment`
  - `cap_enrollment`
  - `num_waitlisted`
- add new route `POST /import/enrollment`
  - need attribute `enrollment_data` as input from file
  - return status 200 with message if success
  - return status 404 with message if failure
- create `EnrollmentUpdater`
- update other rspec accordingly
- create rspec for `EnrollmentUpdater`
- You can use Postman to test the route
  - set the body to `raw` and set the type to `json`
  - put the following text in the body:
```
{
	"enrollment_data": "20179 CSC  CSC108H1F Intro to Comp Prog            LEC0101  YP  01960196��0000000150\n20179 CSC  CSC108H1F Intro to Comp Prog            LEC0201  YP  01960196��0000000142\n20179 CSC  CSC108H1F Intro to Comp Prog            LEC0301  YP  01960196��0000000141\n20179 CSC  CSC108H1F Intro to Comp Prog            LEC0401  YP  01960196��0000000144\n20179 CSC  CSC108H1F Intro to Comp Prog            LEC5101  YP  01960196��0000000162\n20179 CSC  CSC108H1F Intro to Comp Prog            LEC9901  YP  01960196��0000000152\n20181 CSC  CSC108H1S Intro to Comp Prog            LEC0101  YP  01960196��0000000031\n20181 CSC  CSC108H1S Intro to Comp Prog            LEC0201  YP  00600060��0000000022\n20181 CSC  CSC108H1S Intro to Comp Prog            LEC0301  YP  01960196��0000000018\n20181 CSC  CSC108H1S Intro to Comp Prog            LEC5101  YP  01960196��0000000040\n20181 CSC  CSC108H1S Intro to Comp Prog            LEC9901  YP  01960196��0000000024\n20181 CSC  CSC108H1S Intro to Comp Prog            TUT0201  NE  00000000��0000000000\n20181 CSC  CSC108H1S Intro to Comp Prog            TUT0202  NE  00000000��0000000000\n20181 CSC  CSC108H1S Intro to Comp Prog            TUT0203  NE  00000000��0000000000\n20179 CSC  CSC120H1F CompSci for Sciences          LEC0101  Y   01960185��0000000000\n20181 CSC  CSC121H1S Comp Sci for Stats            LEC0101  Y   01960196��0000000052\n20179 CSC  CSC148H1F Intro to Comp Sci             LEC0101  YP  02400240��0000000065"
}
```

### CODE REVIEW

**Comment by simpslandyy** [comment]
Let's re-evaluate if #177 is a hotfix or a feature. @jmzaleski @reidka 
This requires both front-end and back-end support, and it's an additional feature not a bug.
Plus, it looks like this might be deployed later tonight or next week, in which it's bad practice to deploy late Friday afternoon.

**Comment by simpslandyy** [comment]
Note: @jmzaleski  talked to @reidka today, we can contemplate merging, once we've demo'd to Karen

**Comment by reidka** [comment]
@simpslandyy This is definitely not urgent, especially since CP is much higher priority right now.  I thought I might get around to testing this myself.

**Comment by gabriellesc** [comment]
@reidka I had offered @michellemtchai to review this PR, and I'm happy to do so now - unless you would prefer to?

**Comment by reidka** [comment]
@gabriellesc you are definitely welcome to review!

**Comment by gabriellesc** [comment]
:+1:

**Review by gabriellesc — APPROVED** [review]

**Pull request merged**
