### PR TITLE
Parse Preferences in ChassImporter

### PR DESCRIPTION
**Pull request by michellemtchai**
- Run `docker-compose run -eRAILS_ENV=development rails-app rake db:drop db:create db:migrate db:seed db:seed:chass[parse_pref]` to see the different parsing done
- Parsing accuracy can be seen by going to TAPP>unassigned and clicking on each applicant and comparing `raw_pref` with the display `preference`

### CODE REVIEW

**Comment by gabriellesc** [comment]
Given that the text might include any number of unanticipated, non-course related words other than "and" and "or", maybe it would make more sense to approach this as a pattern-matching problem rather than a parsing problem? Specifically, maybe it would make sense to search for the course codes in the text, rather than searching for non-course code-related text, since we can anticipate the former but not the latter? Even in the case of someone just using "and"s/"or"s, they might have a typo and write "ans" rather than "and", and we wouldn't catch that.

Something like (but maybe more intelligent than) constructing a regex of all the course codes in the round (eg. `/(csc108)|(csc104)|(csc120)/i`).

**Comment by gabriellesc** [comment]
Either way, I'd be really interested to see how this performs on real data!

**Comment by michellemtchai** [comment]
@gabriellesc Interesting idea. I'll try that.

**Comment by gabriellesc** [comment]
Sorry to be a pain, but the regexes are a bit difficult to read and parse with the naked eye. Is there any chance you could put a comment beside each regex to describe what it's supposed to match? Or an example of what it would match?

**Review by gabriellesc — APPROVED** [review]

**Pull request merged**
