### PR TITLE
consistent styling for course list/menu across views

### PR DESCRIPTION
**Pull request by gabriellesc**

### CODE REVIEW

**Comment by freeatnet** [comment]
Conflicts :(

**Comment by jmzaleski** [comment]
I posted a screenshot of my old-school conflict viewer to the slack general channel aimed at arseniy and gabrielle. Looks like a one minute resolution for Gabrielle.

**Review by freeatnet — APPROVED** [review]

**Comment by freeatnet** [comment]
After a rebase (consisted of accepting removal of `itemStyle`), here's what the course list looks like:
still-jumpy

Does this look right?

**Comment by gabriellesc** [comment]
Yes, it does: the width will be adjusted, but the height etc. are good.
(Impressive gif embedding!)

**Pull request merged**
