### PR TITLE
appState data container is Immutable, appState functions use Immutable

### PR DESCRIPTION
**Pull request by gabriellesc**
Bugs to fix:
- [x] can't click on course buttons in un/assigned views to go to abc
(**dev note**: this works if the course is already open in the abc view beforehand)

### CODE REVIEW

**Comment by freeatnet** [comment]
I'm having trouble filtering people by "course" in assigned / unassigned views. Not sure if this is a regression specific to this branch, though.

Otherwise, as far as I can tell, everything works beautifully!

**Comment by gabriellesc** [comment]
@freeatnet Do you mean that you have trouble using the UI to do it (clicking, etc.), that there is a latency issue with the filtering being applied, or that the filtering doesn't work properly?

**Comment by freeatnet** [comment]
@gabriellesc I navigate to (un-) assigned view, see some people listed. I click on the course filter and select a course from the dropdown. The list changes, however, not all people in the list have the selected course in their preferences or assignments.

**Comment by gabriellesc** [comment]
@freeatnet That's strange - I don't get that issue with assigned ~(although I haven't had a chance to test it with unassigned)~ or unassigned.
One thing to note is that the courses are not listed in any particular order, so if you filter by course A, you might have to look along through an applicant's preferences to see course A. A quick way to check would be to search in the browser for that course code, with highlighting - then you would expect to see a course highlighted on every applicant row.

Would you be able to give me a specific instance of filtering and the unexpected result?

**Comment by gabriellesc** [comment]
Update (elsewhere) from @freeatnet:
> @gabrielle Checked it out. Everything works on current #133 and after rebuilding stuff. :+1: Awesomesauce!

**Review by reidka — APPROVED** [review]
I've played with these changes and it looks fine to me.  I think it is ready to merge.

**Pull request merged**
